name: CI

on:
  push:
    branches:
      - main
  pull_request:
  # release:
  #   types: [created]

permissions:
  actions: read
  contents: read

env:
  SWC_FORCE_WASM: 1
  NX_DAEMON: 'false'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Cache node_modules
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # - name: Approve builds (if necessary)
      # run: pnpm approve-builds
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm dlx nx run-many -t lint --verbose

      - name: Run tests
        run: pnpm dlx nx run-many -t test --verbose

      - name: Run build
        run: pnpm dlx nx run-many -t build --verbose

      - name: Publish
        if: github.event_name == 'release'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: |
          pnpm dlx nx release publish --verbose
